# typed: strict
# frozen_string_literal: true

# Generated by packaging/generate.mjs — edit that script, not this file.
cask "dsh-studio" do
  arch arm: "aarch64", intel: "x64"

  version "0.7.8"
  sha256 arm:   "3d97529826683efc349e0d852f81fbae71c7a4383f96d237defcea66ea1e41d1",
         intel: "12beaa6adb0ab6032c1fc8001bb352ff01b6ae16aa39a81939b775a9d81ea005"

  url "https://github.com/Moresyl/dsh-studio/releases/download/v#{version}/DSH.Studio_#{version}_#{arch}.dmg"
  name "DSH Studio"
  desc "Native desktop shell for DeepSeek Harness"
  homepage "https://github.com/Moresyl/dsh-studio"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Tauri 2 supports Catalina and later. The binaries are tagged lower than that
  # — 11.0 on arm64, 10.13 on Intel — but the tag is the linker's deployment
  # target, not a claim that the webview underneath it works, so the framework's
  # floor is the one worth declaring.
  depends_on macos: ">= :catalina"

  app "DSH Studio.app"

  # The application's own directory is named after the binary rather than the
  # bundle identifier, because it comes from the cross-platform data path and not
  # from Tauri. It holds the harness and any Node runtime the app downloaded, so
  # it is by far the largest thing to reclaim — a few hundred megabytes.
  #
  # ~/.dsh is deliberately absent. The harness owns that directory and shares it
  # with its own CLI, so removing it here would take a user's harness
  # configuration with an app they merely stopped using.
  zap trash: [
    "~/Library/Application Support/dsh-studio",
    "~/Library/Caches/io.github.moresyl.dshstudio",
    "~/Library/HTTPStorages/io.github.moresyl.dshstudio",
    "~/Library/Preferences/io.github.moresyl.dshstudio.plist",
    "~/Library/Saved Application State/io.github.moresyl.dshstudio.savedState",
    "~/Library/WebKit/io.github.moresyl.dshstudio",
  ]
end
